name: MCBansDetector
main: hide92795.bukkit.plugin.mcbansdetector.MCBansDetector
version: 1.6.2_3
description: Check baned player
author: hide92795
depend: [hide92795CoreLib]
softdepend: [RemoteAdmin]

commands:
  mcbansdetector:
    permission: mcbansdetector
    aliases: [md]
  mcbansdetector-list:
    permission: mcbansdetector.history
    aliases: [mdl]
  mcbansdetector-show:
    permission: mcbansdetector.history
    aliases: [mds]
  mcbansdetector-protect:
    permission: mcbansdetector.protect
    aliases: [mdp]
  mcbansdetector-reload:
    permission: mcbansdetector.reload
    aliases: [mdr]